package jatx.russianrocksongbook.navigation

const val destinationStart = "Start"
const val destinationSongList = "SongList"
const val destinationFavorite = "Favorite"
const val destinationSongText = "SongText"
const val destinationSongTextByArtistAndTitle = "SongTextByArtistAndTitle"
const val destinationCloudSearch = "CloudSearch"
const val destinationCloudSongText = "CloudSongText"
const val destinationTextSearchList = "TextSearchList"
const val destinationTextSearchSongText = "TextSearchSongText"
const val destinationAddArtist = "AddArtist"
const val destinationAddSong = "AddSong"
const val destinationDonation = "Donation"
const val destinationSettings = "Settings"

const val argArtist = "artist"
const val argPosition = "position"
const val argTitle = "argTitle"
const val argIsBackFromSomeScreen = "isBackFromSomeScreen"
const val argIsFromMenu = "isFromMenu"
const val argIsBackFromSong = "isBackFromSong"
const val argCloudSearchRandomKey = "cloudSearchRandomKey"
const val argTextSearchListRandomKey = "textSearchListRandomKey"