# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: AndroidUITests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:         
  uiTestsMacos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Java Heap Size
        run: java -XX:+PrintFlagsFinal -version | grep HeapSize
          
      - name: Gradle Wrapper
        run: gradle wrapper

      - name: Android Tests
        uses: tabatsky/android-emulator-runner@release/v2
        with:
          api-level: 29
          profile: Nexus 6
          arch: x86_64
          ram-size: 1536
          heap-size: 256
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: |
            adb logcat -c
            adb logcat *:E &
            ./gradlew app:connectedAndroidTest
