# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: AndroidDatabaseTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:         
  databaseTestsUbuntu:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Java Heap Size
        run: java -XX:+PrintFlagsFinal -version | grep HeapSize
          
      - name: Gradle Wrapper
        run: gradle wrapper

      - name: Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6
          arch: x86_64
          ram-size: 2048
          heap-size: 512
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: |
            adb logcat -c
            adb logcat *:E &
            ./gradlew data-layer:local:connectedAndroidTest
